### ISSUE TITLE
Bug: fetchUserLatestWeiboByUID 在 UID 非法时会抛出错误

### ISSUE THREAD

**Issue by WendaoLee** [HK-Artificial-Intelligence-Association/WeiboAPI#1]
```log
 Error validating info source: (FiberFailure) Error: 【在获取微博信息源时发生错误::getLatestWeiboByUID】 - matchFetchError:: 获取用户最新微博失败，因为新浪微博接口返回的 ok 状态码不为 1
    at <anonymous> (D:\Backup\Documents\GitHub\Content-crawling-generation-system\src\lib\error\fetchErrorHandler.ts:48:12)
    at D:\Backup\Documents\GitHub\Content-crawling-generation-system\node_modules\effect\src\internal\core-effect.ts:1694:56
```

应该不抛出错误，而是返回空数组

**Comment by WendaoLee** [comment]
想了想，还是 reject 吧。
